### ISSUE TITLE
    img_src.shape[1], img_src.shape[0], img_src) TypeError: drawBoxOfROI() missing 1 required positional argument: 'image_np'

### ISSUE THREAD

**Issue by PR-Iyyer** [zzeitt/Gesture-Recognition#1]
img_src.shape[1], img_src.shape[0], img_src)
TypeError: drawBoxOfROI() missing 1 required positional argument: 'image_np'

what is image_np here..? Can someone pls help?

**Comment by zzeitt** [comment]
Hi @PR-Iyyer ,

As the Error Info suggests, `image_np` is one of the arguments of the function `drawBoxOfROI()`.
Here is the explanation of two main arguments:

- `boxes_roi`:  carrying the position information of detected hands.
- `image_np`: video frame captured by webcam. (suffix '_np' here means nothing, or maybe it hints 'nonprocessed':P )

> You could find `drawBoxOfROI()` in the file `recognizaer_utils.py` line 18 (where it's defined) and `detect_webcam.py` line 38 (where it's called).

**Comment by zzeitt** [comment]
Timed out.
